const ROLES = {
  USER: 'USER',
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
};

const VEHICLE_TYPES = {
  CAR: 'CAR',
  BIKE: 'BIKE',
  EV_CAR: 'EV_CAR',
  EV_BIKE: 'EV_BIKE',
};

const SLOT_TYPES = {
  NORMAL: 'NORMAL',
  EV: 'EV',
  ACCESSIBLE: 'ACCESSIBLE',
  VIP: 'VIP',
};

const SLOT_STATUS = {
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  OCCUPIED: 'OCCUPIED',
  MAINTENANCE: 'MAINTENANCE',
  DISABLED: 'DISABLED',
};

const RESERVATION_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
};

const SESSION_STATUS = {
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
};

const WAITLIST_STATUS = {
  WAITING: 'WAITING',
  ALLOCATED: 'ALLOCATED',
  CANCELLED: 'CANCELLED',
};

const DELIVERY_STATUS = {
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED',
};

const SOURCES = {
  REAL: 'REAL',
  SIMULATION: 'SIMULATION',
};

module.exports = {
  ROLES,
  VEHICLE_TYPES,
  SLOT_TYPES,
  SLOT_STATUS,
  RESERVATION_STATUS,
  SESSION_STATUS,
  WAITLIST_STATUS,
  DELIVERY_STATUS,
  SOURCES,
};
